name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - sqlalchemy==1.4.46
  - postgresql
  - psycopg2
  - pgspecial
  - ipython-sql
  - altair
